### ISSUE TITLE
Getting StringIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by TomerG711** [TremoloSecurity/kubernetes-artifact-deployment#1]
When I run the following command:

curl https://raw.githubusercontent.com/TremoloSecurity/kubernetes-artifact-deployment/master/src/main/bash/deploy_openunison.sh | bash -s /path/to/orchestra-configmaps /path/to/orchestra-secrets https://raw.githubusercontent.com/OpenUnison/openunison-k8s-login-activedirectory/master/src/main/yaml/artifact-deployment.yaml

(Using my path to the folders of course), the artifact-deployment pod gets an Error.
When I look into the pod logs using kubectl log <pod_name> -n openunison-deploy I can see the following error:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1967)
at com.tremolosecurity.kubernetes.artifacts.run.RunDeployment.main(RunDeployment.java:91)

How could this happen?
Looking into the RunDeployment code, it seems that at line 91 it tries to read the deploymentTemplate, and yet it gets an error there.

**Comment by mlbiam** [comment]
going to close as a dupe of https://github.com/OpenUnison/openunison-k8s-login-activedirectory/issues/49
